.text

test0:     addi a1, zero, 0
           addi a2, zero, 0
           addi a3, zero, 0
           mul a0, a1, a2
           beq a0, a3, test1
           ebreak

test1:     addi a1, zero, 0
           addi a2, zero, 1
           addi a3, zero, 1
           mul a0, a1, a2
           beq a0, a3, test2
           ebreak

test2:     addi a1, zero, 0
           addi a2, zero, 4
           addi a3, zero, 2
           mul a0, a1, a2
           beq a0, a3, test3
           ebreak

test3:     addi a1, zero, 0
           addi a2, zero, 9
           addi a3, zero, 3
           mul a0, a1, a2
           beq a0, a3, test4
           ebreak

test4:     addi a1, zero, 0
           addi a2, zero, 16
           addi a3, zero, 4
           mul a0, a1, a2
           beq a0, a3, test5
           ebreak

test5:     addi a1, zero, 0
           addi a2, zero, 25
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test6
           ebreak

test6:     addi a1, zero, 0
           addi a2, zero, 36
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test7
           ebreak

test7:     addi a1, zero, 0
           addi a2, zero, 49
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test8
           ebreak

test8:     addi a1, zero, 0
           addi a2, zero, 64
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test9
           ebreak

test9:     addi a1, zero, 0
           addi a2, zero, 81
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test10
           ebreak

test10:    addi a1, zero, 0
           addi a2, zero, 100
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test11
           ebreak

test11:    addi a1, zero, 0
           addi a2, zero, 121
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test12
           ebreak

test12:    addi a1, zero, 0
           addi a2, zero, 144
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test13
           ebreak

test13:    addi a1, zero, 0
           addi a2, zero, 169
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test14
           ebreak

test14:    addi a1, zero, 0
           addi a2, zero, 196
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test15
           ebreak

test15:    addi a1, zero, 0
           addi a2, zero, 225
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test16
           ebreak

test16:    addi a1, zero, 1
           addi a2, zero, 0
           addi a3, zero, 1
           mul a0, a1, a2
           beq a0, a3, test17
           ebreak

test17:    addi a1, zero, 1
           addi a2, zero, 1
           addi a3, zero, 2
           mul a0, a1, a2
           beq a0, a3, test18
           ebreak

test18:    addi a1, zero, 1
           addi a2, zero, 4
           addi a3, zero, 3
           mul a0, a1, a2
           beq a0, a3, test19
           ebreak

test19:    addi a1, zero, 1
           addi a2, zero, 9
           addi a3, zero, 4
           mul a0, a1, a2
           beq a0, a3, test20
           ebreak

test20:    addi a1, zero, 1
           addi a2, zero, 16
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test21
           ebreak

test21:    addi a1, zero, 1
           addi a2, zero, 25
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test22
           ebreak

test22:    addi a1, zero, 1
           addi a2, zero, 36
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test23
           ebreak

test23:    addi a1, zero, 1
           addi a2, zero, 49
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test24
           ebreak

test24:    addi a1, zero, 1
           addi a2, zero, 64
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test25
           ebreak

test25:    addi a1, zero, 1
           addi a2, zero, 81
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test26
           ebreak

test26:    addi a1, zero, 1
           addi a2, zero, 100
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test27
           ebreak

test27:    addi a1, zero, 1
           addi a2, zero, 121
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test28
           ebreak

test28:    addi a1, zero, 1
           addi a2, zero, 144
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test29
           ebreak

test29:    addi a1, zero, 1
           addi a2, zero, 169
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test30
           ebreak

test30:    addi a1, zero, 1
           addi a2, zero, 196
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test31
           ebreak

test31:    addi a1, zero, 1
           addi a2, zero, 225
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test32
           ebreak

test32:    addi a1, zero, 8
           addi a2, zero, 0
           addi a3, zero, 2
           mul a0, a1, a2
           beq a0, a3, test33
           ebreak

test33:    addi a1, zero, 8
           addi a2, zero, 1
           addi a3, zero, 3
           mul a0, a1, a2
           beq a0, a3, test34
           ebreak

test34:    addi a1, zero, 8
           addi a2, zero, 4
           addi a3, zero, 4
           mul a0, a1, a2
           beq a0, a3, test35
           ebreak

test35:    addi a1, zero, 8
           addi a2, zero, 9
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test36
           ebreak

test36:    addi a1, zero, 8
           addi a2, zero, 16
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test37
           ebreak

test37:    addi a1, zero, 8
           addi a2, zero, 25
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test38
           ebreak

test38:    addi a1, zero, 8
           addi a2, zero, 36
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test39
           ebreak

test39:    addi a1, zero, 8
           addi a2, zero, 49
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test40
           ebreak

test40:    addi a1, zero, 8
           addi a2, zero, 64
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test41
           ebreak

test41:    addi a1, zero, 8
           addi a2, zero, 81
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test42
           ebreak

test42:    addi a1, zero, 8
           addi a2, zero, 100
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test43
           ebreak

test43:    addi a1, zero, 8
           addi a2, zero, 121
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test44
           ebreak

test44:    addi a1, zero, 8
           addi a2, zero, 144
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test45
           ebreak

test45:    addi a1, zero, 8
           addi a2, zero, 169
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test46
           ebreak

test46:    addi a1, zero, 8
           addi a2, zero, 196
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test47
           ebreak

test47:    addi a1, zero, 8
           addi a2, zero, 225
           addi a3, zero, 17
           mul a0, a1, a2
           beq a0, a3, test48
           ebreak

test48:    addi a1, zero, 27
           addi a2, zero, 0
           addi a3, zero, 3
           mul a0, a1, a2
           beq a0, a3, test49
           ebreak

test49:    addi a1, zero, 27
           addi a2, zero, 1
           addi a3, zero, 4
           mul a0, a1, a2
           beq a0, a3, test50
           ebreak

test50:    addi a1, zero, 27
           addi a2, zero, 4
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test51
           ebreak

test51:    addi a1, zero, 27
           addi a2, zero, 9
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test52
           ebreak

test52:    addi a1, zero, 27
           addi a2, zero, 16
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test53
           ebreak

test53:    addi a1, zero, 27
           addi a2, zero, 25
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test54
           ebreak

test54:    addi a1, zero, 27
           addi a2, zero, 36
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test55
           ebreak

test55:    addi a1, zero, 27
           addi a2, zero, 49
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test56
           ebreak

test56:    addi a1, zero, 27
           addi a2, zero, 64
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test57
           ebreak

test57:    addi a1, zero, 27
           addi a2, zero, 81
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test58
           ebreak

test58:    addi a1, zero, 27
           addi a2, zero, 100
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test59
           ebreak

test59:    addi a1, zero, 27
           addi a2, zero, 121
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test60
           ebreak

test60:    addi a1, zero, 27
           addi a2, zero, 144
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test61
           ebreak

test61:    addi a1, zero, 27
           addi a2, zero, 169
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test62
           ebreak

test62:    addi a1, zero, 27
           addi a2, zero, 196
           addi a3, zero, 17
           mul a0, a1, a2
           beq a0, a3, test63
           ebreak

test63:    addi a1, zero, 27
           addi a2, zero, 225
           addi a3, zero, 18
           mul a0, a1, a2
           beq a0, a3, test64
           ebreak

test64:    addi a1, zero, 64
           addi a2, zero, 0
           addi a3, zero, 4
           mul a0, a1, a2
           beq a0, a3, test65
           ebreak

test65:    addi a1, zero, 64
           addi a2, zero, 1
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test66
           ebreak

test66:    addi a1, zero, 64
           addi a2, zero, 4
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test67
           ebreak

test67:    addi a1, zero, 64
           addi a2, zero, 9
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test68
           ebreak

test68:    addi a1, zero, 64
           addi a2, zero, 16
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test69
           ebreak

test69:    addi a1, zero, 64
           addi a2, zero, 25
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test70
           ebreak

test70:    addi a1, zero, 64
           addi a2, zero, 36
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test71
           ebreak

test71:    addi a1, zero, 64
           addi a2, zero, 49
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test72
           ebreak

test72:    addi a1, zero, 64
           addi a2, zero, 64
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test73
           ebreak

test73:    addi a1, zero, 64
           addi a2, zero, 81
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test74
           ebreak

test74:    addi a1, zero, 64
           addi a2, zero, 100
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test75
           ebreak

test75:    addi a1, zero, 64
           addi a2, zero, 121
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test76
           ebreak

test76:    addi a1, zero, 64
           addi a2, zero, 144
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test77
           ebreak

test77:    addi a1, zero, 64
           addi a2, zero, 169
           addi a3, zero, 17
           mul a0, a1, a2
           beq a0, a3, test78
           ebreak

test78:    addi a1, zero, 64
           addi a2, zero, 196
           addi a3, zero, 18
           mul a0, a1, a2
           beq a0, a3, test79
           ebreak

test79:    addi a1, zero, 64
           addi a2, zero, 225
           addi a3, zero, 19
           mul a0, a1, a2
           beq a0, a3, test80
           ebreak

test80:    addi a1, zero, 125
           addi a2, zero, 0
           addi a3, zero, 5
           mul a0, a1, a2
           beq a0, a3, test81
           ebreak

test81:    addi a1, zero, 125
           addi a2, zero, 1
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test82
           ebreak

test82:    addi a1, zero, 125
           addi a2, zero, 4
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test83
           ebreak

test83:    addi a1, zero, 125
           addi a2, zero, 9
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test84
           ebreak

test84:    addi a1, zero, 125
           addi a2, zero, 16
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test85
           ebreak

test85:    addi a1, zero, 125
           addi a2, zero, 25
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test86
           ebreak

test86:    addi a1, zero, 125
           addi a2, zero, 36
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test87
           ebreak

test87:    addi a1, zero, 125
           addi a2, zero, 49
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test88
           ebreak

test88:    addi a1, zero, 125
           addi a2, zero, 64
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test89
           ebreak

test89:    addi a1, zero, 125
           addi a2, zero, 81
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test90
           ebreak

test90:    addi a1, zero, 125
           addi a2, zero, 100
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test91
           ebreak

test91:    addi a1, zero, 125
           addi a2, zero, 121
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test92
           ebreak

test92:    addi a1, zero, 125
           addi a2, zero, 144
           addi a3, zero, 17
           mul a0, a1, a2
           beq a0, a3, test93
           ebreak

test93:    addi a1, zero, 125
           addi a2, zero, 169
           addi a3, zero, 18
           mul a0, a1, a2
           beq a0, a3, test94
           ebreak

test94:    addi a1, zero, 125
           addi a2, zero, 196
           addi a3, zero, 19
           mul a0, a1, a2
           beq a0, a3, test95
           ebreak

test95:    addi a1, zero, 125
           addi a2, zero, 225
           addi a3, zero, 20
           mul a0, a1, a2
           beq a0, a3, test96
           ebreak

test96:    addi a1, zero, 216
           addi a2, zero, 0
           addi a3, zero, 6
           mul a0, a1, a2
           beq a0, a3, test97
           ebreak

test97:    addi a1, zero, 216
           addi a2, zero, 1
           addi a3, zero, 7
           mul a0, a1, a2
           beq a0, a3, test98
           ebreak

test98:    addi a1, zero, 216
           addi a2, zero, 4
           addi a3, zero, 8
           mul a0, a1, a2
           beq a0, a3, test99
           ebreak

test99:    addi a1, zero, 216
           addi a2, zero, 9
           addi a3, zero, 9
           mul a0, a1, a2
           beq a0, a3, test100
           ebreak

test100:   addi a1, zero, 216
           addi a2, zero, 16
           addi a3, zero, 10
           mul a0, a1, a2
           beq a0, a3, test101
           ebreak

test101:   addi a1, zero, 216
           addi a2, zero, 25
           addi a3, zero, 11
           mul a0, a1, a2
           beq a0, a3, test102
           ebreak

test102:   addi a1, zero, 216
           addi a2, zero, 36
           addi a3, zero, 12
           mul a0, a1, a2
           beq a0, a3, test103
           ebreak

test103:   addi a1, zero, 216
           addi a2, zero, 49
           addi a3, zero, 13
           mul a0, a1, a2
           beq a0, a3, test104
           ebreak

test104:   addi a1, zero, 216
           addi a2, zero, 64
           addi a3, zero, 14
           mul a0, a1, a2
           beq a0, a3, test105
           ebreak

test105:   addi a1, zero, 216
           addi a2, zero, 81
           addi a3, zero, 15
           mul a0, a1, a2
           beq a0, a3, test106
           ebreak

test106:   addi a1, zero, 216
           addi a2, zero, 100
           addi a3, zero, 16
           mul a0, a1, a2
           beq a0, a3, test107
           ebreak

test107:   addi a1, zero, 216
           addi a2, zero, 121
           addi a3, zero, 17
           mul a0, a1, a2
           beq a0, a3, test108
           ebreak

test108:   addi a1, zero, 216
           addi a2, zero, 144
           addi a3, zero, 18
           mul a0, a1, a2
           beq a0, a3, test109
           ebreak

test109:   addi a1, zero, 216
           addi a2, zero, 169
           addi a3, zero, 19
           mul a0, a1, a2
           beq a0, a3, test110
           ebreak

test110:   addi a1, zero, 216
           addi a2, zero, 196
           addi a3, zero, 20
           mul a0, a1, a2
           beq a0, a3, test111
           ebreak

test111:   addi a1, zero, 216
           addi a2, zero, 225
           addi a3, zero, 21
           mul a0, a1, a2
           beq a0, a3, end
           ebreak

end:       wfi